@startuml AddFeature_Overall

title Overall Add Flashcard Flow

skinparam sequenceReferenceBackgroundColor #7cb9e8

participant ":QuizMos"
participant "<<class>>\nParser"
participant ":AddFlashcardCommand"
participant "<<class>>\nUi"
participant ":FlashcardList"
participant ":Storage"

":QuizMos" -> "<<class>>\nParser": parseCommand(command)
activate "<<class>>\nParser"

"<<class>>\nParser" -> ":AddFlashcardCommand": <<create>> AddFlashcardCommand(parts)
activate ":AddFlashcardCommand"

":AddFlashcardCommand" -> "<<class>>\nUi": invalidCommandRespond() [if format invalid]
activate "<<class>>\nUi"
"<<class>>\nUi" --> ":AddFlashcardCommand"
deactivate "<<class>>\nUi"

":AddFlashcardCommand" --> "<<class>>\nParser": return AddFlashcardCommand
deactivate ":AddFlashcardCommand"

"<<class>>\nParser" --> ":QuizMos": return AddFlashcardCommand
deactivate "<<class>>\nParser"

":QuizMos" -> ":AddFlashcardCommand": execute(flashcards, storage)
activate ":AddFlashcardCommand"

alt Command invalid
    ":AddFlashcardCommand" -> "<<class>>\nUi": invalidCommandRespond()
    activate "<<class>>\nUi"
    "<<class>>\nUi" --> ":AddFlashcardCommand"
    deactivate "<<class>>\nUi"
else Command valid
    ":AddFlashcardCommand" -> ":FlashcardList": addFlashcard(new Flashcard)
    activate ":FlashcardList"
    ":FlashcardList" --> ":AddFlashcardCommand": Flashcard added
    deactivate ":FlashcardList"

    ":AddFlashcardCommand" -> "<<class>>\nUi": showFlashcardAdded(flashcard)
    activate "<<class>>\nUi"
    "<<class>>\nUi" --> ":AddFlashcardCommand"
    deactivate "<<class>>\nUi"

    ":AddFlashcardCommand" -> ":Storage": writeToFile(flashcards)
    activate ":Storage"
    ":Storage" --> ":AddFlashcardCommand": save successful
    deactivate ":Storage"
end

":AddFlashcardCommand" --> ":QuizMos"
deactivate ":AddFlashcardCommand"
destroy ":AddFlashcardCommand"

@enduml
