@startuml MainComponent_ClassDiagram

title Main Component Class Diagram

skinparam classAttributeIconSize 0
skinparam classBackgroundColor #FFF3E6
skinparam packageStyle rectangle
skinparam shadowing false

package "quizmos" {
    class QuizMos
}

package "quizmos.parser" {
    class Parser
}

package "quizmos.storage" {
    class Storage
}

package "quizmos.ui" {
    class Ui
}

package "quizmos.command" {
    abstract class "{abstract}\nCommand" as Command
}

/' Relationships '/
QuizMos --> FlashcardList : manages >
QuizMos ..> Parser : parses command
QuizMos ..> Command : executes command
QuizMos --> Storage : persists data
QuizMos ..> Ui : interacts with user

@enduml
