@startuml RemoveFeature_Overall

title Overall Remove Flashcard Flow

skinparam sequenceReferenceBackgroundColor #ffcccb

participant ":QuizMos"
participant "<<class>>\nParser"
participant ":RemoveFlashcardCommand"
participant "<<class>>\nUi"
participant ":FlashcardList"
participant ":Storage"

":QuizMos" -> "<<class>>\nParser": parseCommand(command)
activate "<<class>>\nParser"

"<<class>>\nParser" -> ":RemoveFlashcardCommand": <<create>> RemoveFlashcardCommand(arg)
activate ":RemoveFlashcardCommand"
":RemoveFlashcardCommand" --> "<<class>>\nParser": return RemoveFlashcardCommand
deactivate ":RemoveFlashcardCommand"

"<<class>>\nParser" --> ":QuizMos": return RemoveFlashcardCommand
deactivate "<<class>>\nParser"

":QuizMos" -> ":RemoveFlashcardCommand": execute(flashcards, storage)
activate ":RemoveFlashcardCommand"

alt Invalid index
    ":RemoveFlashcardCommand" -> "<<class>>\nUi": invalidIndexRespond()
    activate "<<class>>\nUi"
    "<<class>>\nUi" --> ":RemoveFlashcardCommand"
    deactivate "<<class>>\nUi"
else Valid index
    ":RemoveFlashcardCommand" -> ":FlashcardList": getFlashcard(index)
    activate ":FlashcardList"
    ":FlashcardList" --> ":RemoveFlashcardCommand": Flashcard object
    deactivate ":FlashcardList"

    ":RemoveFlashcardCommand" -> ":FlashcardList": removeFlashcard(index)
    activate ":FlashcardList"
    ":FlashcardList" --> ":RemoveFlashcardCommand": Flashcard removed
    deactivate ":FlashcardList"

    ":RemoveFlashcardCommand" -> "<<class>>\nUi": showFlashcardRemoved(flashcard)
    activate "<<class>>\nUi"
    "<<class>>\nUi" --> ":RemoveFlashcardCommand"
    deactivate "<<class>>\nUi"

    ":RemoveFlashcardCommand" -> ":Storage": writeToFile(flashcards)
    activate ":Storage"
    ":Storage" --> ":RemoveFlashcardCommand": save successful
    deactivate ":Storage"
end

":RemoveFlashcardCommand" --> ":QuizMos"
deactivate ":RemoveFlashcardCommand"
destroy ":RemoveFlashcardCommand"

@enduml
