@startuml SearchFeature_Overall

title Overall Search Flashcard Flow

skinparam sequenceReferenceBackgroundColor #f7e37c

participant ":QuizMos"
participant "<<class>>\nParser"
participant ":SearchFlashcardCommand"
participant "<<class>>\nUi"
participant ":FlashcardList"

":QuizMos" -> "<<class>>\nParser": parseCommand(command)
activate "<<class>>\nParser"

"<<class>>\nParser" -> ":SearchFlashcardCommand": <<create>> SearchFlashcardCommand(keyPhrase)
activate ":SearchFlashcardCommand"
":SearchFlashcardCommand" --> "<<class>>\nParser": return SearchFlashcardCommand
deactivate ":SearchFlashcardCommand"

"<<class>>\nParser" --> ":QuizMos": return SearchFlashcardCommand
deactivate "<<class>>\nParser"

":QuizMos" -> ":SearchFlashcardCommand": execute(flashcards, storage)
activate ":SearchFlashcardCommand"

":SearchFlashcardCommand" -> ":FlashcardList": iterate over flashcards
activate ":FlashcardList"
":FlashcardList" --> ":SearchFlashcardCommand": matching flashcards list
deactivate ":FlashcardList"

alt No matches
    ":SearchFlashcardCommand" -> "<<class>>\nUi": noMatchesRespond()
    activate "<<class>>\nUi"
    "<<class>>\nUi" --> ":SearchFlashcardCommand"
    deactivate "<<class>>\nUi"
else Matches found
    ":SearchFlashcardCommand" -> "<<class>>\nUi": respond(matches.toString())
    activate "<<class>>\nUi"
    "<<class>>\nUi" --> ":SearchFlashcardCommand"
    deactivate "<<class>>\nUi"
end

":SearchFlashcardCommand" --> ":QuizMos"
deactivate ":SearchFlashcardCommand"
destroy ":SearchFlashcardCommand"

@enduml
