@startuml
title Overall Star Flashcard Flow

skinparam dpi 300
skinparam sequenceReferenceBackgroundColor #7cb9e8

participant "<<class>>\n QuizMos" as quizmos
participant "<<class>>\n Parser" as parser
participant "c:StarCommand" as starCommand
participant "flashcards:FlashcardList" as flashcardList
participant "flashcardToBeStarred:Flashcard" as flashcard
participant "<<class>>\n Ui" as ui
participant "storage:Storage" as storage

quizmos -> parser : parseCommand(command : String)
activate parser

parser -> starCommand : <<create>> StarCommand(index : String)
activate starCommand

starCommand --> parser : return StarCommand
deactivate starCommand

parser --> quizmos : return StarCommand
deactivate parser

quizmos -> starCommand : execute(flashcards : FlashcardList, storage : Storage)
activate starCommand

starCommand -> flashcardList : getFlashcard(index : int)
activate flashcardList
flashcardList --> starCommand : flashcardToBeStarred : Flashcard
deactivate flashcardList

starCommand -> flashcard : checkIsStarred()
activate flashcard
flashcard --> starCommand : isStarred : boolean
deactivate flashcard

alt flashcard already starred
starCommand -> :QuizMosInputException : new QuizMosInputException("This flashcard is already starred!")
else flashcard already starred
starCommand -> flashcard : toggleStar()
starCommand -> flashcardList : addStarredFlashcard(flashcardToBeStarred : Flashcard)
starCommand -> ui : showStarredFlashcard(flashcardToBeStarred : Flashcard)
starCommand -> storage : writeToFile(flashcards : FlashcardList)

end
starCommand --> quizmos
deactivate starCommand
destroy starCommand


@enduml
