@startuml StorageComponent_ClassDiagram

title Storage Component Class Diagram

skinparam classAttributeIconSize 0
skinparam classBackgroundColor #FFF3E6
skinparam packageStyle rectangle
skinparam shadowing false

package "storage" {
class Storage {
+Storage(filePath : String)
+load() : ArrayList<Flashcard> throws QuizMosFileException
+writeToFile(flashcards : FlashcardList) : void throws QuizMosInputException
}
}

package "model" {
class Flashcard {
+Flashcard(question : String, answer : String)
+toggleStar() : void
+toSaveFormat() : String
}

class FlashcardList {
+getSize() : int
+getAll() : ArrayList<Flashcard>
}

}

/' Relationships '/
Storage --> Flashcard : uses
Storage --> FlashcardList : uses

@enduml
