@startuml UiComponent_ClassDiagram

title UI Component Class Diagram

skinparam classAttributeIconSize 0
skinparam classBackgroundColor #FFF3E6
skinparam packageStyle rectangle
skinparam shadowing false

package "ui" {
class Ui {
+static isTestMode : boolean
+static readCommand() : String
+static respond(message : String) : void
+static printMessage(message : String) : void
+static printPrompt(message : String) : void
+static printError(message : String) : void
+static respondError(message : String) : void
+static printSeparator() : void
}

class Messages {
+static separator : String
}

}

/' Relationships '/
Ui --> Messages : uses
Ui --> Scanner : uses

@enduml
