@startuml
title Unstar Flashcard Overall Flow

' --- Make PNG large and sharp ---
skinparam dpi 300

skinparam sequenceReferenceBackgroundColor #7cb9e8

participant "<<class>>\n QuizMos" as quizmos
participant "<<class>>\n Parser" as parser
participant "c:UnstarCommand" as unstarCommand
participant "flashcards:FlashcardList" as flashcardList
participant "flashcardToBeUnstarred:Flashcard" as flashcard
participant "<<class>>\n Ui" as ui
participant "storage:Storage" as storage

quizmos -> parser : parseCommand(command : String)
activate parser

parser -> unstarCommand : <<create>> UnstarCommand(index : String)
activate unstarCommand

unstarCommand --> parser : return UnstarCommand
deactivate unstarCommand

parser --> quizmos : return UnstarCommand
deactivate parser

quizmos -> unstarCommand : execute(flashcards : FlashcardList, storage : Storage)
activate unstarCommand

unstarCommand -> flashcardList : getFlashcard(index : int)
activate flashcardList
flashcardList --> unstarCommand : flashcardToBeUnstarred : Flashcard
deactivate flashcardList

unstarCommand -> flashcard : checkIsStarred()
activate flashcard
flashcard --> unstarCommand : isStarred:boolean
deactivate flashcard

alt flashcard already unstarred
unstarCommand -> :QuizMosInputException : new QuizMosInputException("This flashcard is already unstarred!")
else flashcard is starred
unstarCommand -> flashcardList : removeStarredFlashcard(flashcardToBeUnstarred : Flashcard)
unstarCommand -> flashcard : toggleStar()
unstarCommand -> ui : showUnstarredFlashcard(flashcardToBeUnstarred : Flashcard)
unstarCommand -> storage : writeToFile(flashcards : FlashcardList) : void
end

unstarCommand --> quizmos
deactivate unstarCommand
destroy unstarCommand

@enduml
